[workspace]
members = ["basic"

, "hello_tokio", "spawning"]
resolver = "2"

[package]
name = "learn-tokio"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
tokio = { version = "1.42.0", features = ["full"] }
log = "0.4.17"
simple_logger = "4.1.0"
mini-redis = "0.4"
