[workspace]
members = ["basic", "using-log4rs"]
resolver = "2"

[package]
name = "all-about-logging"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
log = "0.4.22"
simple_logger = "5.0.0"

log4rs = "1.3.0"
