[package]
name = "to-do-list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy = "0.3.1"
postgres = "0.19.7"
dotenv = "0.15.0"